dist: trusty
sudo: required

language: node_js
node_js:
  - '8'

cache:
  directories:
    - /tmp/ci-tools
env:
  global:
    - PATH="/tmp/ci-tools:./node_modules/.bin/:$PATH"

before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/mongodb.sh | MONGO_VERSION=2.6.4 sh
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- yarn=1.3.2
install: yarn install
test: yarn test
