// Generated by CoffeeScript 1.8.0
var RestfulResource, dot, _,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

dot = require('dot-component');

_ = require('underscore');

module.exports = RestfulResource = (function() {
  function RestfulResource(Model, schema) {
    this.Model = Model;
    this.schema = schema;
    this._getResourceAndModelFields = __bind(this._getResourceAndModelFields, this);
    this._convertKeysToDotStrings = __bind(this._convertKeysToDotStrings, this);
    this._selectValidResourceSearchFieldsFromQuery = __bind(this._selectValidResourceSearchFieldsFromQuery, this);
    this._extractModelSelectFieldsFromQuery = __bind(this._extractModelSelectFieldsFromQuery, this);
    this._extractLimitFromQuery = __bind(this._extractLimitFromQuery, this);
    this._createModelFromResource = __bind(this._createModelFromResource, this);
    this._createResourceFromModel = __bind(this._createResourceFromModel, this);
    this.send = __bind(this.send, this);
    this.get = __bind(this.get, this);
  }

  RestfulResource.prototype.get = function(paramId) {
    return (function(_this) {
      return function(req, res, next) {
        var id, modelQuery, select;
        id = req.params[paramId];
        select = _this._extractModelSelectFieldsFromQuery(req.query);
        modelQuery = _this.Model.findById(id);
        if (select != null) {
          modelQuery = modelQuery.select(select);
        }
        return modelQuery.exec(function(err, modelFound) {
          if (err) {
            return res.status(400).send(err);
          }
          if (modelFound == null) {
            return res.status(404).send("No " + paramId + " found with id " + id);
          }
          return res.send(_this._createResourceFromModel(modelFound));
        });
      };
    })(this);
  };

  RestfulResource.prototype.query = function() {
    return (function(_this) {
      return function(req, res, next) {
        var dotSearchFields, limit, modelField, modelQuery, resourceField, searchFields, select, value;
        limit = _this._extractLimitFromQuery(req.query);
        select = _this._extractModelSelectFieldsFromQuery(req.query);
        searchFields = _this._selectValidResourceSearchFieldsFromQuery(req.query);
        dotSearchFields = _this._convertKeysToDotStrings(searchFields);
        modelQuery = _this.Model.find();
        for (resourceField in dotSearchFields) {
          value = dotSearchFields[resourceField];
          modelField = _this.schema[resourceField];
          modelQuery = modelQuery.where(modelField).equals(value);
        }
        if (select != null) {
          modelQuery = modelQuery.select(select);
        }
        if (limit != null) {
          modelQuery = modelQuery.limit(limit);
        }
        return modelQuery.exec(function(err, modelsFound) {
          var resources;
          if (err) {
            res.send(400, err);
          }
          resources = modelsFound.map(function(modelFound) {
            return _this._createResourceFromModel(modelFound);
          });
          return res.send(resources);
        });
      };
    })(this);
  };

  RestfulResource.prototype.save = function() {
    return (function(_this) {
      return function(req, res, next) {
        var model, newModelData;
        newModelData = _this._createModelFromResource(req.body);
        model = new _this.Model(newModelData);
        return model.save(function(err, modelSaved) {
          var resource;
          if (err) {
            res.send(400, err);
          }
          resource = _this._createResourceFromModel(modelSaved);
          return res.status(201).send(resource);
        });
      };
    })(this);
  };

  RestfulResource.prototype.update = function(paramId) {
    return (function(_this) {
      return function(req, res, next) {
        var id, newModelData;
        id = req.params[paramId];
        newModelData = _this._createModelFromResource(req.body);
        if (newModelData.updatedAt) {
          newModelData.updatedAt = new Date();
        }
        return _this.Model.findByIdAndUpdate(id, newModelData, function(err, modelUpdated) {
          var resource;
          if (err) {
            res.send(400, err);
          }
          if (!modelUpdated) {
            res.send(404, 'resource not found');
          }
          resource = _this._createResourceFromModel(modelUpdated);
          return res.status(200).send(resource);
        });
      };
    })(this);
  };

  RestfulResource.prototype.send = function(req, res) {
    if (res.body == null) {
      res.body = {};
    }
    return res.send(res.body);
  };

  RestfulResource.prototype._createResourceFromModel = function(model) {
    var modelField, resource, resourceField, value, _ref;
    resource = {};
    _ref = this.schema;
    for (resourceField in _ref) {
      modelField = _ref[resourceField];
      value = dot.get(model, modelField);
      if (value) {
        dot.set(resource, resourceField, value);
      }
    }
    return resource;
  };

  RestfulResource.prototype._createModelFromResource = function(resource) {
    var model, modelField, resourceField, value, _ref;
    model = {};
    _ref = this.schema;
    for (resourceField in _ref) {
      modelField = _ref[resourceField];
      value = dot.get(resource, resourceField);
      if (value) {
        dot.set(model, modelField, value);
      }
    }
    return model;
  };

  RestfulResource.prototype._extractLimitFromQuery = function(query) {
    var limit, _ref;
    limit = (_ref = query.$limit) != null ? _ref : 100;
    delete query.$limit;
    return limit;
  };

  RestfulResource.prototype._extractModelSelectFieldsFromQuery = function(query) {
    var modelFields, modelSelectFields, resourceFields, resourceSelectFields, select, _ref;
    _ref = this._getResourceAndModelFields(), resourceFields = _ref[0], modelFields = _ref[1];
    select = query.$select;
    if (select) {
      if (typeof select === 'string') {
        select = select.split(' ');
      }
      resourceSelectFields = _(select).intersection(resourceFields);
      modelSelectFields = resourceSelectFields.map((function(_this) {
        return function(resourceSelectField) {
          return _this.schema[resourceSelectField];
        };
      })(this));
      modelSelectFields = modelSelectFields.join(' ');
    } else {
      modelSelectFields = modelFields.join(' ');
    }
    delete query.$select;
    return modelSelectFields;
  };

  RestfulResource.prototype._selectValidResourceSearchFieldsFromQuery = function(query) {
    var field, modelFields, queryDotString, resourceFields, validFields, value, _ref;
    queryDotString = this._convertKeysToDotStrings(query);
    _ref = this._getResourceAndModelFields(), resourceFields = _ref[0], modelFields = _ref[1];
    validFields = {};
    for (field in queryDotString) {
      value = queryDotString[field];
      if (__indexOf.call(resourceFields, field) >= 0) {
        dot.set(validFields, field, value);
      }
    }
    return validFields;
  };

  RestfulResource.prototype._convertKeysToDotStrings = function(obj) {
    var dotKeys, dotStringify;
    dotKeys = {};
    dotStringify = function(obj, current) {
      var key, newKey, value, _results;
      _results = [];
      for (key in obj) {
        value = obj[key];
        newKey = current ? current + "." + key : key;
        if (value && typeof value === "object") {
          _results.push(dotStringify(value, newKey));
        } else {
          _results.push(dotKeys[newKey] = value);
        }
      }
      return _results;
    };
    dotStringify(obj);
    return dotKeys;
  };

  RestfulResource.prototype._getResourceAndModelFields = function() {
    var modelFields, resourceFields;
    resourceFields = Object.keys(this.schema);
    modelFields = resourceFields.map((function(_this) {
      return function(resourceField) {
        return _this.schema[resourceField];
      };
    })(this));
    return [resourceFields, modelFields];
  };

  return RestfulResource;

})();
